language: objective-c
osx_image: xcode8
before_install:
  - pod repo update --silent
podfile: demo/Podfile
xcode_workspace: demo/KSYAirStreamer.xcworkspace
xcode_scheme: KSYAirStreamer-Example
script: 
  - xcodebuild clean build -quiet -configuration Release -workspace demo/KSYAirStreamer.xcworkspace -scheme KSYAirStreamer-Example CODE_SIGNING_REQUIRED=NO
